{
    perform: true,
    commands: [
        {
            type: 'label',
            name: '*question',
            action: 'close',
            comment: "Please ask your question on [StackOverflow](https://aka.ms/vscodestackoverflow). We have a great community over [there](https://aka.ms/vscodestackoverflow). They have already answered thousands of questions and are happy to answer yours as well. See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*extension-candidate',
            action: 'close',
            comment: "We try to keep VS Code lean and we think the functionality you're asking for is great for a VS Code extension. Maybe you can already find one that suits your in the [VS Code Marketplace](https://aka.ms/vscodemarketplace). Just in case, in a few simple steps you can get started [writing your own extension](https://aka.ms/vscodewritingextensions). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*not-reproducible',
            action: 'close',
            comment: "We closed this issue because we are unable to reproduce the problem with the steps you describe. Chances are we've already fixed your problem in a recent version of VS Code. If not, please reopen the issue and provide us with more detail. Our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines might help you with that.\n\nHappy Coding!"
        },
        {
            type: 'label',
            name: '*out-of-scope',
            action: 'close',
            comment: "Thanks for your idea! Unfortunately, we won't be able to implement it in the next 12 months. If you wonder what we are up to, please see our [roadmap](https://aka.ms/vscoderoadmap). We close issues that are not covered by the [roadmap](https://aka.ms/vscoderoadmap) to keep the number of issues manageable. Thanks for understanding. As always, pull requests are welcome! See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
        {
            type: 'comment',
            name: 'duplicate',
            action: 'updateLabels',
            addLabel: '*duplicate'
        },
        {
            type: 'label',
            name: '*duplicate',
            allowTriggerByBot: true,
            action: 'close',
            comment: "Thanks for creating this issue! We figured it's covering the same as another one we already have. Thus, we closed this one as a duplicate. You can search for existing issues [here](https://aka.ms/vscodeissuesearch). See also our [issue reporting](https://aka.ms/vscodeissuereporting) guidelines.\n\nHappy Coding!"
        },
    ]
}
